name: pro_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_riverpod: ^0.12.1
  toast: ^0.1.5
  flare_flutter: ^2.0.4
  smart_flare: any
  retrofit: any
  logger: any
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  json_annotation: ^3.1.1
  equatable: ^1.2.5
  shared_preferences: ^0.5.12+4
  freezed_annotation:
  sp_util:
  pull_to_refresh: 1.6.3
  lottie: ^0.7.0+1
  transparent_image: ^1.0.0
  extended_image: ^1.5.0
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  freezed:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home.png
    - assets/images/Listview.png
    - assets/images/history.png
    - assets/images/wode.png
    - assets/images/off_home.png
    - assets/images/off_Listview.png
    - assets/images/off_history.png
    - assets/images/off_wode.png
    - assets/images/icon.png
    - assets/images/icon_accountAbout.png
    - assets/images/icon_accountNumber.png
    - assets/images/icon_accountPassword.png
    - assets/images/animationImage.gif
    - assets/Teddy.flr
    - assets/button-animation.flr
    - assets/slideout-menu.flr
    - assets/json/empty.json
    - assets/json/disconnect.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/loadingYellow.json
    - assets/json/loading2.json
    - assets/json/error2.json
    - assets/json/empty2.json
    - assets/json/empty3.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
  - family: FZDaLTJ
    fonts:
      - asset: assets/fonts/fzDaLTJ.ttf
  - family: FZFWQingYinTiJWL
    fonts:
      - asset: assets/fonts/fzFWQingYinTiJWL.ttf
  - family: FZFWZhuZiAYuanJWM
    fonts:
      - asset: assets/fonts/fzFWZhuZiAYuanJWM.ttf
  - family: SourceHanSans
    fonts:
      - asset: assets/fonts/sourceHanSansMedium.ttc
  - family: Rzzyt
    fonts:
      - asset: assets/fonts/rzzyt.ttf
  - family: IconFont
    fonts:
        - asset: assets/fonts/iconfont.ttf

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
